# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QtForm\FormDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 241)
        MainWindow.setMaximumSize(QtCore.QSize(321, 241))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_apikey = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_apikey.setGeometry(QtCore.QRect(10, 10, 301, 20))
        self.lineEdit_apikey.setObjectName("lineEdit_apikey")
        self.pushButton_connect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_connect.setGeometry(QtCore.QRect(10, 162, 301, 31))
        self.pushButton_connect.setFlat(False)
        self.pushButton_connect.setObjectName("pushButton_connect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SteamApi"))
        self.lineEdit_apikey.setPlaceholderText(_translate("MainWindow", "Введите steam api ключ"))
        self.pushButton_connect.setText(_translate("MainWindow", "Connect"))
